/**:
  ros__parameters:
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    publish_tf: true
    two_d_mode: false

    sensor_timeout: 0.3
    use_sim_time: false

    frequency: 30.0

    # X,  Y,   Z
    # r,  p,   y,
    # X' ,Y',  Z'
    # r', p',  y'
    # X'',Y'', Z''

    odom0: robot/odom
    odom0_config: [true,  true,  false,
                   false, false, false,
                   false, false, false,
                   false, false, true,
                   true,  true, false]
    odom0_differential: false
    odom0_queue_size: 10

    imu0: sensor/imu/data
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,
                  true,  true,  false]
    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 5
    imu0_pose_rejection_threshold: 0.8                 
    imu0_twist_rejection_threshold: 0.8                
    imu0_linear_acceleration_rejection_threshold: 0.8  
    imu0_remove_gravitational_acceleration: true