/**:

  joy_node:
    ros__parameters:
      deadzone: 0.1
      autorepeat_rate: 20.0
      dev: "/dev/input/js0"

  # joy_teleop configuration:
  #   ros__parameters:
  #     deadzone: 0.1
  #     autorepeat_rate: 20.0
  #     # device_name: "Logitech Gamepad F710" # To get the device name: ros2 run joy joy_enumerate_devices 
    
  teleop_twist_joy_node:
    ros__parameters:
      axis_linear:
        x: 1
        y: 0
      scale_linear:
        x: 0.4
        y: 0.4
      scale_linear_turbo:
        x: 1.0
        y: 1.0
      axis_angular:
        yaw: 3
      scale_angular:
        yaw: 0.6
      scale_angular_turbo:
        yaw: 1.2
      enable_button: 4
      enable_turbo_button: 5
